import Database from 'better-sqlite3';
import 'dotenv/config';

const db = new Database(process.env.DATABASE_PATH || './data/platform.db');

db.exec(`
  CREATE TABLE IF NOT EXISTS scuole (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL UNIQUE);
  CREATE TABLE IF NOT EXISTS ausili (id INTEGER PRIMARY KEY AUTOINCREMENT, inv_id INTEGER UNIQUE, codice TEXT, nome TEXT NOT NULL, categoria TEXT, posizione_attuale TEXT DEFAULT 'magazzino', posizione_tipo TEXT DEFAULT 'magazzino', note TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS spostamenti (id INTEGER PRIMARY KEY AUTOINCREMENT, ausilio_id INTEGER NOT NULL, da TEXT NOT NULL, a TEXT NOT NULL, data DATETIME DEFAULT CURRENT_TIMESTAMP, note TEXT, FOREIGN KEY (ausilio_id) REFERENCES ausili(id));
  CREATE TABLE IF NOT EXISTS segnalazioni (id INTEGER PRIMARY KEY AUTOINCREMENT, tipo TEXT NOT NULL, urgente INTEGER DEFAULT 0, scuola TEXT NOT NULL, ausilio_id INTEGER, ausilio_nome TEXT, note TEXT, email_funzionario TEXT NOT NULL, nome_funzionario TEXT NOT NULL, stato TEXT DEFAULT 'in_attesa', data_chiusura DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (ausilio_id) REFERENCES ausili(id));
  CREATE INDEX IF NOT EXISTS idx_ausili_posizione ON ausili(posizione_attuale);
  CREATE INDEX IF NOT EXISTS idx_segnalazioni_stato ON segnalazioni(stato);
  CREATE INDEX IF NOT EXISTS idx_spostamenti_ausilio ON spostamenti(ausilio_id);
`);

const insertScuola = db.prepare('INSERT OR IGNORE INTO scuole (nome) VALUES (?)');
const scuoleList = ['Magazzino', 'Centro Diurno Arcipelago', 'Istituto Suore Immacolatine', 'Liceo King', 'Liceo Mazzini', 'Scuola Inf. Aquilone', 'Scuola Inf. Bertani', 'Scuola Inf. Ca di Ventura', 'Scuola Inf. Chighizzola', 'Scuola Inf. Emanuela Loi', 'Scuola Inf. Jean Piaget', 'Scuola Inf. Mongolfiera', 'Scuola Inf. Monticelli', 'Scuola Inf. Primavera', 'Scuola Inf. Via Bologna', "Scuola Inf. Via Sant'Elia", 'Scuola Inf. Villa Parodi', 'Scuola Inf./Prim. Fabrizi', 'Scuola Inf./Prim. Mameli', 'Scuola Mat. Lomellini', 'Scuola Mat. Mongolfiera', 'Scuola Mat. Rondine', 'Scuola Polo Teglia', 'Scuola Prim. A. Cantore', 'Scuola Prim. Anna Frank', 'Scuola Prim. Barrili', 'Scuola Prim. De Amicis Rivarolo', 'Scuola Prim. De Amicis Voltri', 'Scuola Prim. Elsa Morante', 'Scuola Prim. Emanuelli', 'Scuola Prim. Fermi', 'Scuola Prim. Ferrero', 'Scuola Prim. Gianni Rodari', 'Scuola Prim. Govi', 'Scuola Prim. Jessie Mario', 'Scuola Prim. Papa Giovanni XXIII', 'Scuola Prim. Perasso', 'Scuola Prim. Santullo', 'Scuola Prim. SPINOLA', "Scuola Sec. I° M. D'Azeglio", 'Scuola Sec. I° Nino Bixio', 'Scuola Sec. I° Rizzo Alessi', 'Scuola Sec. I° Luca Cambiaso', 'Scuola Sec.I° Quarto Ex Strozzi', 'Scuola Sec. II° Pertini'];
for (const s of scuoleList) insertScuola.run(s);

const ins = db.prepare('INSERT OR IGNORE INTO ausili (inv_id, codice, nome, categoria, posizione_attuale, posizione_tipo) VALUES (?, ?, ?, ?, ?, ?)');

// MAGAZZINO
ins.run(1024, "SIB260459", "SEGGIOLONE POLIFUNZIONALE  BLU ID 1190  BASE DEL SEGGIOLONE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1190, "298391", "SEGGIOLONE POLIFUNZIONALE  ID 1024 accessori -cuscinetti -fodere -pettorina -tavolino -poggiatesta", "", "magazzino", "magazzino");
ins.run(1107, "SIB269692", "STABILIZZATORE  MINI STANDY COLORE ARANCIONE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1116, "SIB272222", "STABILIZZATORE MINI STANDY", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1117, "SIB272223", "CARROZZINA LEGGERA ACTION JUNIOR  ROSSA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1121, "SIB67623", "TAVOLO DA LAVORO GANBE COLOR NERO  PIANO PLASTICA GRIGIO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1205, "SIB277065", "TAVOLO ABC", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1209, "SIB279604", "SEGGIOLONE EDS", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1212, "SIB279593", "SISTEMA DI POSTURA PALL LOCKEY 4  IMBOTTITURA COLOR ARANCIONE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1221, "SIB279598", "SEGGIOLONE LECKEY  NEW MYGO STRUTTURA  METALLO NERO IMBOTTITURA ARANCIONE CON TAVOLINO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1235, "SIB279999", "DEAMBULATORE STABILIZZATORE MK4   ROSSO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1237, "SIB279996", "SEDIA FEDALE IN LEGNO  ROSSA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1242, "SIB280006", "SEGGIOLONE  LECKEY  MIS. 3   STRUTTURA  METALLO NERO IMBOTTITURA  ROSA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1252, "SIB287993", "SISTEMA DI SEDUTA PAL", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1267, "SIB288272", "DEAMBULATORE GRILLO  BIANCO E VERDE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1268, "SIB288275", "PASSEGGINO LISA  BLU", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1348, "SIB291441", "DEAMBULATORE CROCCODILE R82  ARANCIONE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1352, "SIB291400", "DEAMBULATORE NIMBO ALL MOBILITY VERDE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1361, "SIB291466", "SOLLEVATORE ELETRICO GEMINI", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1363, "SIB291803", "STABILIZZATORE MYGO  ARANCIONE  NERO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1384, "SIB296817", "STABILIZZATORE MYGO  ARANCIONE  NERO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1474, "SIB298176", "STABILIZZATORE PER STATICA IN POSTURA ERETTA, CON STRUTTURA VERTICALE REGOLABILE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1475, "SIB298177", "STABILIZZATORE PER STATICA IN POSTURA PRONA CON SISTEMA DI FISSAGGIO AL TAVOLO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1481, "SIB298183", "RIALZO STABILIZZANTE PER WC CIAMB / BAMB", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1496, "SIB298198", "DEAMBULATORE SCORREVOLE SU QUATTRO RUOTE PIROETTANTI CON FRENO DI STAZIONAMENTO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1501, "SIB298203", "STABILIZZATORE PER STATICA IN POSIZIONE PRONA, CON SISTEMA DI INCLINAZIONE INCORPORATO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1512, "SIB298214", "PASSEGGINO RIDUCIBILE E/O CHIUDIBILE PER TRASPORTO ALL'ESTERNO DI BAMBINI  BLU CON RUOTE GRANDI", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1519, "SIB298221", "STABILIZZATORE DEAMBULATORE IN POSIZIONE ERETTA CON SOSTEGNO DEL TRONCO MOVIE GO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1524, "SIB298226", "STABILIZZATORE PER STATICA IN POSTURA ERETTA, CON STRUTTURA VERTICALE REGOLABILE  ARANCIONE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1530, "SIB298232", "STABILIZZATORE MOBILE IN POSTURA ERETTA, MISURA PICCOLA PER BAMBINI SINO A 94 CM  VERDE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1535, "SIB298237", "STABILIZZATORE PER STATICA IN POSTURA ERETTA, MODELLO CON STRUTTURA A TELAIO   JENX", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1537, "SIB298239", "DEAMBULATORE SCORREVOLE SU QUATTRO RUOTE PIROETTANTI CON FRENO DI STAZIONAMENTO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1541, "SIB298243", "STABILIZZATORE PER STATICA IN POSTURA ERETTA, CON STRUTTURA VERTICALE REGOLABILE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1548, "SIB298250", "DEAMBULATORE SCORREVOLE SU QUATTRO RUOTE PIROETTANTI SENZA FRENO METALLO GRIGIO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1553, "SIB298255", "SEGGIOLONE NORMALE  MINERVA AZZURRA BLANDINO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1556, "SIB298258", "SEGGIOLINA IN LEGNO ROSSA CON RUOTE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1557, "SIB298259", "SEGGIOLONE ORTOPEDIZZATO POLIFUNZIONALE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1559, "SIB298261", "CARROZZINA AD AUTOSPINTA SUPERLEGGERA  BLU", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1609, "SIB300309", "Tavolo ad incavo ormesa", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1614, "SIB300312", "STATICA KANGAROO MEDIMEC", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1802, "SIB302641", "LETTINO MEDICO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1806, "302640", "DEAMBULATORE MEYWALK  VIOLA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1810, "SIB302644", "seggiolone leckey", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1839, "SIB304325", "SEDIA HEATHFIELD MISURA 5 PROGETTIAMO AUTONOMIA ROSSA IN LEGNO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1846, "SIB304320", "SEDIA HEATHFIEL MIS. 1  ROSSA IN LEGNO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1867, "SIB304318", "deambulatore rifton Dynamic pacer sb  NERO  MISURA GRANDE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1872, "SIB305333", "SEDIA MINERVA  STRUTTURA ROSSA  IMB  GRIGIA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1891, "SIB305407", "DEAMBULATORE NIMBO  VERDE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1902, "SIB318830", "SEGGIOLONE R82  LECKEY  BLU E NERO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1905, "318842", "DEAMBULATORE NIMBO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1906, "SIB318844", "MINI SATANDY ORMESA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1917, "SIB318856", "SEGGIOLINA HEATHFIELD MISURA 2  ROSSA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(2025, "SIB327344", "TAVOLO CON INCAVO ORMESA MISURA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(2027, "SIB327346", "SOLLEVATORE ELETTRICO N115/140", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(2070, "SIB331552", "MONTASCALE SCOIATTOLO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(2080, "SIB331561", "SEDIA BLU", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(2084, "SIB333712", "seggiolone leckey struttura metallo nero imbottitura grigia  e viola", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(281, "SIB187805", "DEAMBULATORE 2R2P AZZURRO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(398, "SIB166495", "STABILIZZATORE STATICA MINI STANDY", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(460, "SIB297133", "LETTINO CAMBIO IGIENICO  STRUTTURA IN METALLO  IMB VERDE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(587, "SIB62968", "SEDIA HATFIELD  SEGGIOLINA IN LEGNO  ROSSA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(729, "SIB209728", "TAVOLO SCOLASTICO ABC  GAMBE ROSSA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(754, "SIB79038", "SEDIA IMBOTTITA COLOMBO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(906, "SIB242138", "DEAMBULATORE POSTERIORE KEY CARE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(919, "SIB241628", "STABILIZZATORE REX OSD   KANGOROO", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(945, "SIB244845", "BARELLA DA DOCCIA IDRAULICA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(948, "SIB251616", "STABILIZZATORE SCIMMIA", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(976, "SIB251836", "SEDIA COLOMBO  VERDE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(1484, "SIB298186", "DEAMBULATORE SCORREVOLE SU QUATTRO RUOTE", "COMUNE DI GENOVA", "magazzino", "magazzino");
ins.run(2109, "335880", "TAVOLO SCHOOL MISURA VN1007-8-1 TAVOLO MIS 1", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2110, "335881", "SISTEMA DI SEDUTA PAL SISTEMA DI SEDUTA PAL 135-3600-01 - MIS. 3 VERDE TAVOLINO E INSERTO IMBOTT. 135-3620 - TAVOL MIS 3 CUNEO DIVARICATORE 135-360", "SEGGIOLA", "magazzino", "magazzino");
ins.run(2111, "335882", "TAVOLO ORMESA MULTIFUNZIONE MIS LARGE", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2125, "335902", "SEDIA DA BAGNO SCHIENALE ALTO SIZE 1", "ACCESSORI", "magazzino", "magazzino");
ins.run(2126, "335903", "SEDIA BAGNO SCHIENALE ALTO SIZE 2", "ACCESSORI", "magazzino", "magazzino");
ins.run(2127, "335904", "SEDIA BAGNO SCHIENALE BASSO 1", "ACCESSORI", "magazzino", "magazzino");
ins.run(2128, "335905", "SEDIA BAGNO SCHIENALE BASSO 2", "ACCESSORI", "magazzino", "magazzino");
ins.run(2135, "335917", "SISTEMA DI SEDUTA PAL 135-1600-03 - MIS. 1 AZZURRO TAVOLINO E INSERTO IMBOTT. 135-1620 - TAVOL. MIS 1 BASI OPZIONALI 135-1610 BASE CON RUOTE MIS", "SEGGIOLA", "magazzino", "magazzino");
ins.run(2136, "335918", "SISTEMA DI SEDUTA PAL 135-1600-03 - MIS. 1 AZZURRO TAVOLINO E INSERTO IMBOTT. 135-1620 - TAVOL. MIS 1 BASI OPZIONALI 135-1610 BASE CON RUOTE MIS", "SEGGIOLA", "magazzino", "magazzino");
ins.run(2137, "335919", "SISTEMA DI SEDUTA PAL 135-2600-01 - MIS. 2 VERDE TAVOLINO E INSERTO IMBOTT. 135-2620 - TAVOL. MIS 2 BASI OPZIONALI 135-2610 BASE CON RUOTE MIS", "SEGGIOLA", "magazzino", "magazzino");
ins.run(2138, "335920", "SISTEMA DI SEDUTA PAL 135-2600-01 - MIS. 2 VERDE TAVOLINO E INSERTO IMBOTT. 135-2620 - TAVOL. MIS 2 BASI OPZIONALI 135-2610 BASE CON RUOTE MIS", "SEGGIOLA", "magazzino", "magazzino");
ins.run(2139, "335921", "SISTEMA DI SEDUTA PAL 135-3600-03 - MIS. 3 AZZURRO TAVOLINO E INSERTO IMBOTT. 135-3620 - TAVOL. MIS 3 BASI OPZIONALI 135-3610 BASE CON RUOTE MIS.", "SEGGIOLA", "magazzino", "magazzino");
ins.run(2140, "335922", "SISTEMA DI SEDUTA PAL 135-3600-03 - MIS. 3 AZZURRO TAVOLINO E INSERTO IMBOTT. 135-3620 - TAVOL. MIS 3 BASI OPZIONALI 135-3610 BASE CON RUOTE MIS.", "SEGGIOLA", "magazzino", "magazzino");
ins.run(2141, "335923", "TAVOLO ORMESA MULTIFUNZIONE MIS SMALL", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2142, "335924", "TAVOLO ORMESA MULTIFUNZIONE MIS SMALL", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2143, "335925", "TAVOLO ORMESA MULTIFUNZIONE MIS SMALL", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2144, "335926", "TAVOLO ORMESA MULTIFUNZIONE MIS MEDIUM", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2145, "335927", "TAVOLO ORMESA MULTIFUNZIONE MIS MEDIUM", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2146, "335928", "TAVOLO ORMESA MULTIFUNZIONE MIS MEDIUM", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2147, "335929", "TAVOLO ORMESA MULTIFUNZIONE MIS LARGE", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2148, "335930", "TAVOLO ORMESA MULTIFUNZIONE MIS LARGE", "TAVOLO LAVORO", "magazzino", "magazzino");
ins.run(2149, "335931", "TAVOLO ORMESA MULTIFUNZIONE MIS LARGE", "TAVOLO LAVORO", "magazzino", "magazzino");

// SCUOLE
ins.run(2148, "SIB57587", "PEDANA IN LEGNO", "", "Scuola Mat. Rondine", "scuola");
ins.run(2102, "SIB260491", "DIVARICATORE REGOLABILE", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(1994, "SIB34907", "RULLO RIGIDO IN GOMMA PIUMA INDEFORMABILE", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2070, "SIB266448", "SEGGIOLINA HATFIELD", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2041, "SIB266444", "TAVOLO DA LAVORO", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2088, "SIB269694", "TAPPETO OM AZZURRO", "", "Scuola Sec. I° M. D'Azeglio", "scuola");
ins.run(2096, "SIB272715", "TAPPETONE", "", "Scuola Prim. Elsa Morante", "scuola");
ins.run(2078, "SIB272771", "2 TAPPETI DA PARETE", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2068, "SIB272768", "TAVOLO AD INCAVO", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(1993, "SIB272767", "TAVOLO AD INCAVO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2092, "SIB274057", "SEGGIOLINA HATFIELD", "", "Scuola Sec.I° Quarto Ex Strozzi", "scuola");
ins.run(2072, "SIB275277", "TAVOLO SCOLASTICO ABC", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2059, "SIB275275", "TOILETTE SEAT CHAIR", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(1988, "SIB275908", "SEGGIOLONE POLIFUNZIONALE", "", "CENTRO DIURNO ARCIPELAGO", "scuola");
ins.run(1986, "SIB275908", "ACCESSORI SEGGIOLONE 11002", "", "CENTRO DIURNO ARCIPELAGO", "scuola");
ins.run(1987, "SIB2759008", "ACCESSORI SEGGIOLONE 11002", "", "CENTRO DIURNO ARCIPELAGO", "scuola");
ins.run(2069, "SIB276405", "BARELLA DOCCIA", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2032, "SIB276403", "CINTURA PELVICA", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(1996, "SIB230564", "BARELLA DOCCIA SANIX", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2127, "SIB230555", "BARELLA DOCCIA SANIX", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2085, "SIB279695", "TAVOLO DA LAVORO", "", "Liceo Mazzini", "scuola");
ins.run(2015, "SIB280002", "STABILIZZATORE POSTERIORE", "", "Scuola Prim. A. Cantore", "scuola");
ins.run(2103, "SIB288238", "BARELLA DOCCIA ELETTRICA", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2064, "SIB288239", "LETTINO CON PEDALIERA ELETTRICA", "", "Liceo King", "scuola");
ins.run(2049, "SIB288240", "SEDIA HATFIELD", "", "Scuola Prim. Fermi", "scuola");
ins.run(2048, "SIB288241", "SEDIA PAL", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2082, "SIB288276", "LETTINO DA VISITA", "", "Scuola Prim. Emanuelli", "scuola");
ins.run(2065, "SIB288396", "SOLLEVATORE OLEODINAMICO GEMINI", "", "Liceo King", "scuola");
ins.run(2042, "SIB288397", "SOLLEVATORE ELETTRICO", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2130, "SIB288400", "TAPPETO 1", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2045, "SIB2884001", "TAPPETO 2", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2046, "SIB288402", "TAPPETO 3", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2108, "SIB288403", "TAPPETO 4", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2062, "SIB288404", "TAPPETO", "", "Scuola Prim. Jessie Mario", "scuola");
ins.run(2131, "SIB288405", "TAPPETO 2", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(1997, "SIB297231", "SOLLEVATORE ELETTRICO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2128, "SIB288621", "LETTINO IN LEGNO BLU MARINO", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2104, "SIB288620", "VERTICALIZZATORE ELETTRICO", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2031, "SIB288622", "SEGGIOLONE CON BASE PER INTERNI", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(1983, "SIB291447", "ARMADIO LEGNO CON SERRATURA", "", "Scuola Prim. Anna Frank", "scuola");
ins.run(1984, "SIB291448", "ARMADIO LEGNO CON SERRATURA", "", "Scuola Prim. Anna Frank", "scuola");
ins.run(1998, "SIB291449", "ARMADIO IN LEGNO CON SERRATURA", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(1999, "SIB291450", "ARMADIO IN LEGNO CON SERRATURA", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2044, "SIB297998", "ARMADIO IN LEGNO CON SERRATURA", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2106, "SIB298296", "ARMADIO LEGNO 6", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2107, "SIB298297", "ARMADIO LEGNO 7", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2129, "SIB291459", "ARMADIO IN LEGNO - 8 - CON SERRATURA", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2073, "SIB291454", "ARMADIO LEGNO", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2074, "SIB291455", "ARMADIO LEGNO", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2029, "SIB291451", "ARMADIO IN LEGNO CON SERRATURA", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2154, "SIB291456", "ARMADIO LEGNO CON SERRATURA", "", "Scuola Polo Teglia", "scuola");
ins.run(2155, "SIB291457", "ARMADIO LEGNO CON SERRATURA", "", "Scuola Polo Teglia", "scuola");
ins.run(2033, "SIB291399", "MINI STANDY", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2052, "SIB291439", "TAVOLO DA LAVORO ORMESA", "", "Scuola Prim. Ferrero", "scuola");
ins.run(2051, "SIB291443", "DEAMBULATORE POSTERIORE NIMBO", "", "Scuola Prim. Ferrero", "scuola");
ins.run(2152, "SIB291431", "SISTEMA DI SEDUTA PAL", "", "Scuola Prim. SPINOLA", "scuola");
ins.run(2017, "SIB291372", "TAVOLO DA LAVORO RECLINABILE", "", "Scuola Inf. Chighizzola", "scuola");
ins.run(2080, "SIB291463", "SISTEMA DI SEDUTA PAL", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2105, "SIB291802", "LETTO BLU BASE LEGNO", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2043, "SIB291800", "LETTO BASE LEGNO BLU", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2109, "SIB296824", "PARETE MORBIDA", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2110, "SIB296625", "(COPY)PARETE MORBIDA 1", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2075, "SIB296828", "PARETE MORBIDA 4", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2076, "SIB296829", "PARETE MORBIDA 5", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2156, "SIB296830", "PARETE MORBIDA 6", "", "Scuola Polo Teglia", "scuola");
ins.run(2157, "SIB296831", "PARETE MORBIDA 7", "", "Scuola Polo Teglia", "scuola");
ins.run(2091, "SIB296818", "LETTINO BASSO BASE LEGNO", "", "Scuola Sec.I° Quarto Ex Strozzi", "scuola");
ins.run(2030, "SIB296822", "LETTINO CON BASE IN LEGNO", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2077, "SIB296823", "LETTINO BASE LEGNO", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2135, "SIB296808", "TAPPETO 1", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2136, "SIB296809", "PARETE MORBIDA", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2139, "SIB296812", "PARETE MORBIDA", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2018, "SIB296813", "TAPPETO 200X100X30", "", "Scuola Inf. Chighizzola", "scuola");
ins.run(2087, "SIB296758", "SISTEMA DI POSTURA MADITA OTTOBOCK", "", "Scuola Sec. I° M. D'Azeglio", "scuola");
ins.run(2143, "SIB190716", "CILINDRO IMBOTTITO", "", "Scuola Prim. Gianni Rodari", "scuola");
ins.run(2145, "SIB190717", "PARALLELEPIPEDO IN GOMMA", "", "Scuola Prim. Gianni Rodari", "scuola");
ins.run(2144, "SIB190714", "ARMADIO 2 ANTINE", "", "Scuola Prim. Gianni Rodari", "scuola");
ins.run(2146, "SIB230557", "ARMADIO INFERMERIA IN VETRO", "", "Scuola Prim. Gianni Rodari", "scuola");
ins.run(2000, "SIB35082", "CUBO RIGIDO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2001, "SIB254612", "CUBO RIGIDO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2002, "SIB34909", "CUNEO MORBIDO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2003, "SIB34910", "CUNEO MORBIDO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2004, "SIB34914", "MATERASSONE 200X140X5 CM", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2006, "SIB260497", "PARALLELEPIPEDO IN GOMMA", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2007, "SIB254613", "PARALLELEPIPEDO IN GOMMA", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2005, "SIB260498", "PARALLELEPIPEDO IN GOMMA", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2008, "SIB156260", "SEMICILINDRO CM50", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2009, "SIB156258", "SEMICILINDRO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2010, "SIB35079", "TAPPETO BICOLORE", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2012, "SIB57486", "TAPPETO GIALLO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2013, "SIB180448", "TAVOLO CON INCAVO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2014, "SIB65542", "CUNEO IN GOMMA PIUMA", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2159, "SIB66749", "CUSCINO A CUNEO", "", "Scuola Polo Teglia", "scuola");
ins.run(2161, "SIB66810", "TAPPETO GOMMA SPUGNA", "", "Scuola Polo Teglia", "scuola");
ins.run(2163, "SIB66836", "CUSCINO A TRAPEZIO IN GOMMA PIUMA", "", "Scuola Polo Teglia", "scuola");
ins.run(2165, "SIB66838", "CUSCINO CUNEO GOMMA PIUMA", "", "Scuola Polo Teglia", "scuola");
ins.run(2169, "SIB66872", "TAPPETINO IN GOMMA", "", "Scuola Polo Teglia", "scuola");
ins.run(2166, "SIB66857", "MANIGLIONE BIANCO PER BAGNO", "", "Scuola Polo Teglia", "scuola");
ins.run(2167, "SIB66868", "TAPPETO MORBIDONE", "", "Scuola Polo Teglia", "scuola");
ins.run(2168, "SIB66869", "SACCONE PARALLELEPIPEDO IN SKY", "", "Scuola Polo Teglia", "scuola");
ins.run(2170, "SIB66873", "CUSCINO SEMICERCHIO", "", "Scuola Polo Teglia", "scuola");
ins.run(2171, "SIB66874", "TAPPETO- PISCINA", "", "Scuola Polo Teglia", "scuola");
ins.run(2172, "SIB69454", "CILINDRO IN GOMMA", "", "Scuola Polo Teglia", "scuola");
ins.run(2174, "SIB155387", "CUSCINO CILINDRO", "", "Scuola Polo Teglia", "scuola");
ins.run(2111, "SIB288406", "SOLLEVATORE ELETTRICO", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2047, "SIB298000", "SISTEMA POSTURALE  EDS EVERYDAY ACTIVITY SETAT", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2120, "SIB80766", "STRUTTURA PISCINA", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2079, "SIB241276", "ARMADIETTO INFERMERIA", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2113, "SIB71436", "TAPPETO MORBIDO BLU", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2114, "SIB198978", "TAPPETO CON MANICI", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2115, "SIB71437", "CUSCINO A CUNEO COLORE BLU", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2116, "SIB164979", "CUSCINO SEMICILINDRICO ROSSO E VERDE", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2117, "SIB209719", "CUSCINO CUNEO PER BARELLA", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2122, "SIB296814", "TAPPETO 103 DIM", "", "Scuola Inf. Primavera", "scuola");
ins.run(2123, "SIB296815", "PARETE DOLCE ONDA ALBICOCCA", "", "Scuola Inf. Primavera", "scuola");
ins.run(2124, "SIB296816", "PARETE DOLCE ONDA ALBICOCCA", "", "Scuola Prim. De Amicis Rivarolo", "scuola");
ins.run(2147, "SIB239583", "CUSCINO A CUNEO CHINESPORT", "", "Scuola Prim. Gianni Rodari", "scuola");
ins.run(2094, "SIB298182", "SEGGIOLONE ORTOPEDIZZATO POLIFUNZIONALE", "", "Scuola Sec.I° Quarto Ex Strozzi", "scuola");
ins.run(1934, "SIB56838", "SEDIA ORMESA PICCOLISSIMA", "", "Scuola Inf. Monticelli", "scuola");
ins.run(1940, "SIB298193", "SEGGIOLONE ORTOPEDIZZATO POLIFUNZIONALE", "", "Scuola Inf. Jean Piaget", "scuola");
ins.run(1936, "SIB298197", "BASE DI SOSTEGNO PER INTERNI, PER SISTEMI DI POSTURA", "", "Scuola Mat. lomellini", "scuola");
ins.run(1957, "SIB298242", "DEAMBULATORE SCORREVOLE SU QUATTRO RUOTE PIROETTANTI SENZA FRENO", "", "Scuola Inf. Mongolfiera", "scuola");
ins.run(2118, "SIB298246", "TAVOLINO CON INCAVO E CON REGOLAZIONE DELL'ALTEZZA", "", "Scuola Prim. Papa Giovanni XXIII", "scuola");
ins.run(2083, "SIB298253", "TAVOLINO CON INCAVO E CON REGOLAZIONE DELL'ALTEZZA", "", "Scuola Prim. Emanuelli", "scuola");
ins.run(2036, "SIB298267", "TAVOLINO CON INCAVO E CON REGOLAZIONE DELL'ALTEZZA", "", "Scuola Prim. Anna Frank", "scuola");
ins.run(2090, "SIB298705", "BARELLA DOCCIA CHINESPORT", "", "Scuola Sec.I° Quarto Ex Strozzi", "scuola");
ins.run(2207, "SIB299406", "TAVOLO CON INCAVO", "", "Scuola Inf. Chighizzola", "scuola");
ins.run(2201, "299421", "sedia a rotelle rehacare globalcare grigia e nera", "", "Scuola Prim. Barrili", "scuola");
ins.run(1989, "SIB187253", "TAVOLO ORMESA", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2200, "SIB302638", "STATICA ORMESA MINI STANDY MIS. 2", "", "Scuola Inf. Ca di Ventura", "scuola");
ins.run(2192, "302639", "SEGGIOLONE KOALA", "", "Scuola Inf. Aquilone", "scuola");
ins.run(2186, "SIB304309", "STABILIZZATORE MINI STANDY ORMESA -MIS. 3", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2253, "SIB304331", "seggiolina in legno imbottitura verde", "", "Scuola Inf. Jean Piaget", "scuola");
ins.run(2196, "SIB30430", "SEGGIOLONE MADITA(NO FUN)", "", "Scuola Mat. mongolfiera", "scuola");
ins.run(2179, "304329", "SEGGIOLONE MADITA FUN MIS. 2", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2181, "SIB318843", "DEAMBULATORE ETAC CROCODILE MIS. 2", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2187, "SIB318860", "DEAMBULATORE GRILLO MARCA ORMESA TAGLIA M", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2190, "SIB318854", "SISTEMA DI POSTURA MADITA FUN MIS.2", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2197, "SIB318858", "LETTINO DA ESAMI", "", "Scuola Prim. Santullo", "scuola");
ins.run(2184, "SIB318859", "BARELLA DOCCIA ADULTI", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2202, "SIB323522", "SEGGIOLINA PICCOLA ROSSA", "", "Scuola Inf. Mongolfiera", "scuola");
ins.run(2212, "SIB327320", "CARROZZINA PIEGHEVOLE START4 M2", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2211, "SIB331534", "SISTEMA POSTURA : X PANDA", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2210, "SIB331536", "SEGGIOLONE POSTURALE ETAC X PANDA", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2199, "SIB331538", "SEDUTA POSTURALE CRYSTAL, MISURA 1", "", "Scuola Inf. Villa Parodi", "scuola");
ins.run(2189, "SIB331543", "tavolo gambe rosse", "", "Scuola Inf. Bertani", "scuola");
ins.run(2204, "SIB331549", "TAVOLO AD INCAVO", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2183, "331550", "SEDIA BAGNO FLAMINGO HIGH-LOW ETC MIS. 2", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2255, "SIB331547", "SEGGIOLINA HEATHFIELD MIS 3", "", "Scuola prim. Govi", "scuola");
ins.run(2191, "SIB333729", "SEGGIOLONE ORTOPEDIZZATO POLIFUNZIONALE", "", "Scuola Inf. Jean Piaget", "scuola");
ins.run(2214, "SIB334573", "SDEGGIOLINA", "", "Scuola Inf. Chighizzola", "scuola");
ins.run(2215, "SIB334611", "SEGGIOLONE LEKEY PAL", "", "Scuola Inf. Via Bologna", "scuola");
ins.run(2112, "SIB187471", "TAVOLO LAVORO", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2100, "SIB187833", "TAVOLO TANDARD", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2101, "SIB187834", "TAVOLO STANDARD", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2056, "SIB56090", "FASCIATOIO", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(1995, "SIB198324", "CUNEO MORBIDO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2028, "SIB77162", "TAVOLO AD INCAVO", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2125, "SIB31973", "SOLLEVATORE", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2061, "SIB77097", "FASCIATOIO", "", "Scuola Inf. Via Sant'Elia", "scuola");
ins.run(1982, "SIB207023", "ARMADIO FARMACI 05/06", "", "Scuola Prim. Anna Frank", "scuola");
ins.run(2023, "SIB207024", "ARMADIO FARMACI", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2066, "SIB207025", "ARMADIO FARMACI", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2067, "SIB207027", "ARMADIO FARMACI BIANCO IN VETRO", "", "Scuola Inf./Prim. Mameli", "scuola");
ins.run(2024, "SIB207031", "RAMPA DI ACCESSO", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2119, "SIB207032", "RAMPA DI ACCESSO", "", "Scuola Prim. Perasso", "scuola");
ins.run(2142, "SIB207033", "LETTINO ELETTRICO", "", "Scuola Prim. Gianni Rodari", "scuola");
ins.run(2099, "SIB198979", "TAPPETO", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2040, "SIB77417", "SEDIA SITTING", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(2034, "SIB184457", "STABILIZZATORE MINI STANDY 3", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2055, "SIB63345", "FASCIATOIO", "", "Scuola Inf. Emanuela Loi", "scuola");
ins.run(2019, "SIB36105", "FRIGORIFERO PER FARMACI", "", "Scuola Sec. I° M. D'Azeglio", "scuola");
ins.run(1990, "SIB35083", "CUNEO COLOMBO MOD. 88", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2153, "SIB66855", "TAPPETO BLU 300X350X3", "", "Scuola Polo Teglia", "scuola");
ins.run(1991, "SIB34913", "RULLO MORBIDO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2084, "SIB187257", "TAVOLO DA LAVORO 425 GRANDE", "", "Scuola Prim. Emanuelli", "scuola");
ins.run(2026, "SIB209235", "RAMPA DI ACCESO PER ELEMENTARE DE AMICIS", "", "Scuola Prim. De Amicis Voltri", "scuola");
ins.run(2057, "SIB209743", "TAVOLO AD INCAVO", "", "Scuola Inf./Prim. Fabrizi", "scuola");
ins.run(1992, "SIB220033", "TAVOLO DA LAVORO AD INCAVO", "", "Scuola Sec I° Luca Cambiaso", "scuola");
ins.run(2126, "SIB230528", "TAVOLO ORMESA", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2097, "SIB62969", "CUSCINO A CUNEO CHINESPORT", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(2098, "SIB241277", "LETTINO FASCIATOIO", "", "Scuola Sec. I° Nino Bixio", "scuola");
ins.run(1946, "SIB251603", "SEDIA COLOMBO SITTING", "", "Scuola Inf. Bertani", "scuola");
ins.run(2086, "SIB251599", "TAVOLO COLOMBO", "", "Scuola Sec. I° M. D'Azeglio", "scuola");
ins.run(2121, "SIB251585", "TAVOLO ORMESA", "", "Scuola Sec II° Pertini", "scuola");
ins.run(2054, "SIB251578", "TAVOLO COLOMBO - SCOL", "", "ISTITUTO SUORE IMMACOLATINE", "scuola");
ins.run(2151, "SIB251573", "SOLLEVATORE OLEODINAMICO", "", "Scuola Prim. Santullo", "scuola");
ins.run(2141, "SIB35086", "TAVOLO DA LAVORO GRANDE", "", "Scuola Sec. I° Rizzo Alessi", "scuola");
ins.run(2050, "SIB253562", "SEDIA COLOMBO", "", "Scuola Prim. Fermi", "scuola");

console.log('Database inizializzato con tutti gli ausili.');
db.close();